# modules/desktop-sway-open.nix — the sway desktop (agentos.desktop = "sway"; surfaces-and-first-login.md
# §6/§9 item 4: "then sway"). OPEN variant only, imported by configuration-open.nix; inert unless chosen.
#
# Its job is to prove the desktop adapter is not shaped around one compositor: the same brain, the same
# brain-home window on workspace 1, the same human bindings, a different compositor and adapter
# (agos_desktop.SwayAdapter, swaymsg). Deliberately smaller than the Hyprland desktop: sway's own bar
# instead of waybar, no animations, no game/cheatsheet rules. Audio and brightness come from
# desktop-open.nix's always-on block.
#
# THE BRAIN WINDOW: same unit shape as the Hyprland desktop (a systemd user unit that the compositor only
# pokes, Restart=always, the in-window respawn loop, journal tee), keyed on app_id `brain-home`.
{ config, pkgs, lib, ... }:

let
  user = "agent";
  term = config.agentos.surfaceInternal.terminalCmd;

  swayConf = pkgs.writeText "sway-config" ''
    # Agent OS sway desktop (generated by modules/desktop-sway-open.nix; edits are overwritten).
    set $mod Mod4
    font pango:DejaVu Sans 10
    default_border pixel 2
    gaps inner 6

    # The brain lives on workspace 1. Keyed to the dedicated app_id, not to every kitty.
    assign [app_id="brain-home"] workspace number 1
    for_window [app_id="brain-home"] border none

    # The session environment reaches the user manager before the brain unit is poked (same reason as
    # the Hyprland desktop: the unit, not a bare exec, owns the window's lifetime).
    exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP
    exec systemctl --user restart brain-home.service

    bindsym $mod+Return exec ${term}
    bindsym $mod+b exec firefox
    bindsym $mod+d exec wofi --show drun
    bindsym $mod+r exec wofi --show drun
    bindsym $mod+q kill
    bindsym $mod+f fullscreen toggle
    bindsym $mod+v floating toggle
    bindsym $mod+Shift+m exit
    bindsym $mod+1 workspace number 1
    bindsym $mod+2 workspace number 2
    bindsym $mod+3 workspace number 3
    bindsym $mod+4 workspace number 4
    bindsym $mod+5 workspace number 5
    bindsym $mod+Shift+1 move container to workspace number 1
    bindsym $mod+Shift+2 move container to workspace number 2
    bindsym $mod+Shift+3 move container to workspace number 3
    bindsym $mod+Shift+4 move container to workspace number 4
    bindsym $mod+Shift+5 move container to workspace number 5
    bindsym $mod+Left focus left
    bindsym $mod+Right focus right
    bindsym $mod+Up focus up
    bindsym $mod+Down focus down

    # Fn keys (same tools as the Hyprland desktop).
    bindsym XF86AudioRaiseVolume exec wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+
    bindsym XF86AudioLowerVolume exec wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
    bindsym XF86AudioMute exec wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
    bindsym XF86MonBrightnessUp exec brightnessctl set 5%+
    bindsym XF86MonBrightnessDown exec brightnessctl set 5%-

    bar {
      position top
      status_command while date +'%a %d %b  %H:%M'; do sleep 30; done
    }
  '';
in
lib.mkIf (config.agentos.desktop == "sway") {
  system.build.swayConf = swayConf;

  programs.sway = {
    enable = true;
    wrapperFeatures.gtk = true;
  };

  xdg.portal = {
    enable = true;
    wlr.enable = true;
    extraPortals = [ pkgs.xdg-desktop-portal-gtk ];
  };

  fonts.packages = with pkgs; [ dejavu_fonts ];

  systemd.user.services.brain-home = {
    description = "agent-brain home window (the desktop's primary surface)";
    path = [ config.programs.sway.package ];
    serviceConfig = {
      ExecStart = "${pkgs.kitty}/bin/kitty --class brain-home -e ${pkgs.bash}/bin/bash -c 'exec 3>&2; while :; do /run/current-system/sw/bin/agent-brain 2> >(${pkgs.coreutils}/bin/tee -i >(${pkgs.systemd}/bin/systemd-cat -t agent-brain) >&3); sleep 1; done'";
      Restart = "always";
      RestartSec = 2;
    };
  };

  environment.systemPackages = with pkgs; [
    firefox kitty wofi grim slurp wl-clipboard xdg-utils wireplumber brightnessctl
  ];

  systemd.tmpfiles.rules = [
    "d /home/${user}/.config 0755 ${user} users - -"
    "d /home/${user}/.config/sway 0755 ${user} users - -"
    "L+ /home/${user}/.config/sway/config - - - - ${swayConf}"
  ];

  # Autologin drops us on tty1 as `agent`; start sway there only (SSH ptys are /dev/pts/*).
  environment.loginShellInit = ''
    if [ -z "''${WAYLAND_DISPLAY:-}" ] && [ "$(tty)" = "/dev/tty1" ]; then
      exec sway
    fi
  '';
}
